POST http://127.0.0.1:5000/movies/
Accept: text/plain
Content-Type: application/json

{
  "description": "Наследник знаменитого дома Атрейдесов Пол отправляется вместе с семьей на одну из самых опасных планет во Вселенной — Арракис. Здесь нет ничего, кроме песка, палящего солнца, гигантских чудовищ и основной причины межгалактических конфликтов — невероятно ценного ресурса, который называется меланж. В результате захвата власти Пол вынужден бежать и скрываться, и это становится началом его эпического путешествия. Враждебный мир Арракиса приготовил для него множество тяжелых испытаний, но только тот, кто готов взглянуть в глаза своему страху, достоин стать избранным.",
  "director_id": 11,
  "genre_id": 7,
  "id": 21,
  "rating": 8.4,
  "title": "See no sound",
  "trailer": "https://www.youtube.com/watch?me",
  "year": 2021
}

<> 2021-11-17T165515.200.json



###

PUT http://127.0.0.1:5000/movies/1
Accept: text/plain
Content-Type: application/json

{
  "description": "Наследник Пол отправляется из Вселенной. Здесь нет ничего. В результате это становится началом его испытаний",
  "director_id": 2,
  "genre_id": 11,
  "rating": 2.4,
  "title": "Crrrreek",
  "trailer": "https://www.youtube.com/watch?me",
  "year": 2022
}


<> 2021-11-17T164739.201.json

###

DELETE http://127.0.0.1:5000/movies/2
Content-Type: application/json